name: roxygen

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        container: rocker/tidyverse:3.6.2
        steps:
            - uses: actions/checkout@v2
              with:
                path: pkgsource

            - name: "check if manuals are upto date with roxygen comments"
              run: |
                Rscript -e "roxygen2::roxygenize('pkgsource', roclets = c('rd', 'collate', 'namespace'))"
